### ISSUE TITLE
No Module Named 'zoo'

### ISSUE THREAD

**Issue by yeamusic21** [intel-analytics/analytics-zoo#1224]
I followed all the steps via pip install using Python 3.6 on Linux VM.  I type 'python' and try the sample code but I get a module not found error :(.

**Comment by yeamusic21** [comment]
I think I solved this problem actually.  I was using the elephant scale VM which was giving me SPARK_HOME issues.  I started a clean VM running Ubuntu 18 and this appears to be resolved. :-D

**Comment by dhannya34** [comment]
![Screenshot from 2019-12-27 16-02-35](https://user-images.githubusercontent.com/44765574/71513937-7c283e00-28c2-11ea-81b9-61a0726869ca.png)

Could you please resolve this issue.

**Comment by qiyuangong** [comment]
Hi @dhannya34 I just reopened this issue for you. 

@hkvision

**Comment by dhannya34** [comment]
Thanks! @qiyuangong

**Comment by hkvision** [comment]
Hi @dhannya34 Seems that you haven't successfully installed analytics-zoo in your environment. You can follow the steps here to install and verify: https://analytics-zoo.github.io/0.6.0/#PythonUserGuide/install/#install-from-pip-for-local-usage
https://analytics-zoo.github.io/0.6.0/#PythonUserGuide/run/#example-code

Or you can show us your installation steps and environment so that we can help you spot the problem.
Thanks.

**Comment by helenlly** [comment]
@dhannya34  could you pls provide the info as requested above? thanks

**Comment by helenlly** [comment]
@dhannya34 we 'll close the issue since no update  for a long time. Pls free to reopen if you have more questions, thanks.
