### ISSUE TITLE
VNNI Python example

### ISSUE THREAD

**Issue by hhbyyh** [intel-analytics/analytics-zoo#1427]
Customer is interesting in the performance improvement from VNNI, and asking if we can have python example for it.

**Comment by qiyuangong** [comment]
@hkvision Do we need to change python API for Zoo VNNI model?

VNNI OpenVINO Python API is ready (#1392). We can prepare a Python example after merging this PR.

But, according to #1425,  passing data from Python to Scala need optimization, otherwise the latency will be much higher than Scala & JAVA API.

**Comment by hkvision** [comment]
@jason-dai

**Comment by hkvision** [comment]
For BigDL VNNI, I suppose there won't be many APIs unexposed in Python. We can draft an example if needed. Possibly the performance will not be as good as Scala.

**Comment by qiyuangong** [comment]
@hhbyyh We have just added a [OpenVINO resnet_v1_50 python example with VNNI support](https://github.com/intel-analytics/analytics-zoo/tree/master/pyzoo/zoo/examples/vnni/openvino).  

Note that as previous mentioned performance issue related to `py4j` has not been resolved yet, the performance benefit may be less than scala example.

**Comment by hhbyyh** [comment]
Thanks for the example. Closing the issue.
