### ISSUE TITLE
[Python] Python package requirements

### ISSUE THREAD

**Issue by andresaco** [intel-analytics/analytics-zoo#1782]
After checking the code and building the package using a fork of this repository, I have seen two issues on the python package being built:

* __The dependencies are fixed__. Using the == operator for pinning dependencies enforces developers to use a specific version of spark/bigdl/conda-pack. It should be better to use a `~=` instead of the current `==`
* __Consistent `install_requires`__.Compiling analytics-zoo against a different pyspark/bigdl version does not update the install_requires argument in `pyzoo/setup.py` file. This no-change causes to install pyspark==2.4.3, bigdl==0.9.0 even if your custom library has not been made on those versions.

**Comment by andresaco** [comment]
FYI, check the Dockerfile at [ai-moma/analytics-zoo-builder](https://github.com/ai-moma/analytics-zoo-builder/tree/feature/initial-release) to see how we compile the library, and how we change the pyspark and bigdl requirements with the correct values.

**Comment by hkvision** [comment]
Hi @andresaco 

Thanks so much. We have already made plans to enhance pip install in the future release.

I suppose we can make it configurable to support building against different spark versions. However, for BigDL version, I think it would be safer to make it fixed for each analytics-zoo version? Since for each branch (release), we ought to support the latest BigDL and if you want to use lower versions, some new BigDL functionalities would be lost and may cause compilation error.

**Comment by hkvision** [comment]
This is kind of duplicate with https://github.com/intel-analytics/analytics-zoo/issues/1748
I close this issue and let's move our discussion to that one.
