### ISSUE TITLE
How to make practical application based on automl ? 

### ISSUE THREAD

**Issue by 2017wxyzwxyz** [intel-analytics/analytics-zoo#2670]
I'm learning time series analysis and prediction. The environment of ‘analytics-zoo automl ’ has been set up.The  tutoiral    'nyc_taxi_dataset.ipynb'  can be run correctly.
         However, after the model training is completed and the indicators meet the requirements, when the actual situation is applied, when the new data has been generated, which function can be called to predict the next possible value (invisible), i.e. out of sample prediction, the tutoiral  'nyc_taxi_dataset.ipynb'  does not give the example code，please help !

**Comment by yushan111** [comment]
I think we have demonstrated that in nyc taxi example as 
```python
pred_df = pipeline.predict(test_df)
```
where test_df is invisible during training process, since we only used train_df and val_df for training. The pipeline predicts the future `future_seq_len` values with length of `look_back` of historical values. So the pred_df corresponds to the prediction value of `test_df[start + look_back, end + future_seq_len]`.
You can also use the pipeline for evaluation on the unseen test dataset or save/restore/incremental training. They are all demonstrated in the notebook.

**Comment by 2017wxyzwxyz** [comment]
Thinks! Itry it.

**Comment by helenlly** [comment]
@2017wxyzwxyz  thanks for your questions. Anything more we can help on this issue? if no, we'd like to close it.

**Comment by helenlly** [comment]
@2017wxyzwxyz  since no reponse on this issue over 3 months, we will close it and you can re-open if you have more questions.
