### ISSUE TITLE
jenkins: chronos_nyc_taxi_tsdataset_forecaster missing 1 required positional argument

### ISSUE THREAD

**Issue by pinggao187** [intel-analytics/analytics-zoo#4476]
#1 start example for chronos_nyc_taxi_tsdataset_forecaster
~~~
Traceback (most recent call last):
  File "/opt/work/jenkins/workspace/ZOO-NB-Colab-Pytorch/docs/docs/colab-notebook/chronos/chronos_nyc_taxi_tsdataset_forecaster.py", line 123, in <module>
    res = forecaster.fit((x, y), epochs=3)
TypeError: fit() missing 1 required positional argument: 'y'
~~~
jenkins link:
http://10.112.231.51:18888/view/ZOO-NB/job/ZOO-NB-Colab-Pytorch/197/console

**Comment by TheaperDeng** [comment]
This issue is caused by different behavior between ZOO-NB-Colab-Pytorch and ZOO-PR-Colab-Pytorch. 
- ZOO-NB-Colab-Pytorch: `pip install --pre analytics-zoo`, which means it will use the latest version of pypi built, b20210809 at this moment.
- ZOO-PR-Colab-Pytorch: use PR branch merged on master.

So before next version of pypi built's release, the test will remain fail if someone change the api of a colab notebook. Solutions can be:

- run ZOO-WEEKLY-Publish-PyPI now and then run ZOO-NB-Colab-Pytorch again.
- Wait for next pypi built, which is scheduled on 0816

**Comment by pinggao187** [comment]
pass
http://10.112.231.51:18888/view/ZOO-NB/job/ZOO-NB-Colab-Pytorch/201/
